{\rtf1\ansi\ansicpg1252\cocoartf2867
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red83\green83\blue83;
\red203\green203\blue202;\red72\green139\blue206;\red213\green213\blue212;\red101\green118\blue135;\red36\green168\blue106;
\red167\green197\blue151;}
{\*\expandedcolortbl;;\cssrgb\c0\c1\c1;\cssrgb\c100000\c100000\c100000;\cssrgb\c40132\c40132\c39981;
\cssrgb\c83411\c83411\c83099;\cssrgb\c34356\c61927\c84545;\cssrgb\c86559\c86558\c86234;\cssrgb\c46966\c53664\c60155;\cssrgb\c14037\c70592\c49283;
\cssrgb\c71061\c80852\c65647;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 --QUERY 1: Show revenue generated by each payment method for confirmed payments\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  \
    p\cf2 \strokec7 .\cf2 \strokec5 payment_method \cf2 \strokec6 AS\cf2 \strokec5  "Payment Method"\cf2 \strokec7 ,\cf2 \strokec5  \
    COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Number of Payments"\cf2 \strokec7 ,\cf2 \strokec5  \
    CONCAT\cf2 \strokec7 (\cf2 \strokec9 '$'\cf2 \strokec7 ,\cf2 \strokec5  SUM\cf2 \strokec7 (\cf2 \strokec5 p\cf2 \strokec7 .\cf2 \strokec5 amount\cf2 \strokec7 ))\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Total Revenue"\cf2 \strokec7 ,\cf2 \strokec5  \
    CONCAT\cf2 \strokec7 (\cf2 \strokec9 '$'\cf2 \strokec7 ,\cf2 \strokec5  ROUND\cf2 \strokec7 (\cf2 \strokec5 AVG\cf2 \strokec7 (\cf2 \strokec5 p\cf2 \strokec7 .\cf2 \strokec5 amount\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 2\cf2 \strokec7 ))\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Average Payment"\cf2 \strokec7 ,\cf2 \strokec5 \
    CONCAT\cf2 \strokec7 (\cf2 \strokec5 ROUND\cf2 \strokec7 (\cf2 \strokec5 COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec10 100.0\cf2 \strokec5  \cf2 \strokec8 /\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec6 SELECT\cf2 \strokec5  COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 FROM\cf2 \strokec5  payments \cf2 \strokec6 WHERE\cf2 \strokec5  payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 2\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec9 '%'\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Market Share"\
\cf2 \strokec6 FROM\cf2 \strokec5  payments p\
\cf2 \strokec6 WHERE\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5  \
\cf2 \strokec6 GROUP\cf2 \strokec5  BY p\cf2 \strokec7 .\cf2 \strokec5 payment_method\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY SUM\cf2 \strokec7 (\cf2 \strokec5 p\cf2 \strokec7 .\cf2 \strokec5 amount\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 -- QUERY 2: Passenger distribution by nationality \cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  \
    nationality \cf2 \strokec6 AS\cf2 \strokec5  "Nationality"\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Passenger Count"\cf2 \strokec7 ,\cf2 \strokec5 \
    CONCAT\cf2 \strokec7 (\cf2 \strokec5 ROUND\cf2 \strokec7 (\cf2 \strokec5 COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec10 100.0\cf2 \strokec5  \cf2 \strokec8 /\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec6 SELECT\cf2 \strokec5  COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 FROM\cf2 \strokec5  passengers\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 2\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec9 '%'\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Percentage"\
\cf2 \strokec6 FROM\cf2 \strokec5  passengers \
\cf2 \strokec6 GROUP\cf2 \strokec5  BY nationality \
\cf2 \strokec6 ORDER\cf2 \strokec5  BY COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 -- QUERY 3: Flights with airline info \cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  \
    f\cf2 \strokec7 .\cf2 \strokec5 flight_number \cf2 \strokec6 AS\cf2 \strokec5  "Flight"\cf2 \strokec7 ,\cf2 \strokec5 \
    a\cf2 \strokec7 .\cf2 \strokec5 airline_name \cf2 \strokec6 AS\cf2 \strokec5  "Airline"\cf2 \strokec7 ,\cf2 \strokec5 \
    a\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec6 AS\cf2 \strokec5  "Airline Country"\cf2 \strokec7 ,\cf2 \strokec5 \
    f\cf2 \strokec7 .\cf2 \strokec5 departure_time \cf2 \strokec6 AS\cf2 \strokec5  "Departure"\cf2 \strokec7 ,\cf2 \strokec5 \
    f\cf2 \strokec7 .\cf2 \strokec5 arrival_time \cf2 \strokec6 AS\cf2 \strokec5  "Arrival"\cf2 \strokec7 ,\cf2 \strokec5 \
    CONCAT\cf2 \strokec7 (\cf2 \strokec9 '$'\cf2 \strokec7 ,\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Price"\cf2 \strokec7 ,\cf2 \strokec5 \
    \cf2 \strokec6 CASE\cf2 \strokec5  \
        \cf2 \strokec6 WHEN\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 available_seats \cf2 \strokec8 >\cf2 \strokec5  \cf2 \strokec10 100\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec9 'High Availability'\cf2 \strokec5 \
        \cf2 \strokec6 WHEN\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 available_seats \cf2 \strokec8 >\cf2 \strokec5  \cf2 \strokec10 50\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec9 'Medium Availability'\cf2 \strokec5 \
        \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec9 'Low Availability'\cf2 \strokec5 \
    \cf2 \strokec6 END\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Seat Status"\
\cf2 \strokec6 FROM\cf2 \strokec5  flights f\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 INNER\cf2 \strokec5  \cf2 \strokec8 JOIN\cf2 \strokec5  airlines a \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 airline_id \cf2 \strokec8 =\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec8 IN\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec9 'Turkey'\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 'Morocco'\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 'Germany'\cf2 \strokec7 )\cf2 \strokec5 \
\cf2 \strokec6 ORDER\cf2 \strokec5  BY f\cf2 \strokec7 .\cf2 \strokec5 price \cf2 \strokec6 DESC\cf2 \strokec7 ,\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 -- QUERY 4: Popular Routes Analysis )\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  \
    CONCAT\cf2 \strokec7 (\cf2 \strokec5 dep\cf2 \strokec7 .\cf2 \strokec5 city\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 ' \uc0\u8594  '\cf2 \strokec7 ,\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 city\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  route\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_bookings\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_revenue\cf2 \strokec7 ,\cf2 \strokec5 \
    MIN\cf2 \strokec7 (\cf2 \strokec5 f\cf2 \strokec7 .\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  cheapest_ticket\cf2 \strokec7 ,\cf2 \strokec5 \
    MAX\cf2 \strokec7 (\cf2 \strokec5 f\cf2 \strokec7 .\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  most_expensive_ticket\cf2 \strokec7 ,\cf2 \strokec5 \
    ROUND\cf2 \strokec7 (\cf2 \strokec5 AVG\cf2 \strokec7 (\cf2 \strokec5 f\cf2 \strokec7 .\cf2 \strokec5 price\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 2\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  average_price\
\cf2 \strokec6 FROM\cf2 \strokec5  flights f\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  airports dep \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 departure_airport_id \cf2 \strokec8 =\cf2 \strokec5  dep\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  airports arr \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 arrival_airport_id \cf2 \strokec8 =\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 flight_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\cf2 \strokec6 GROUP\cf2 \strokec5  BY dep\cf2 \strokec7 .\cf2 \strokec5 city\cf2 \strokec7 ,\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 city\cf2 \strokec7 ,\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 departure_airport_id\cf2 \strokec7 ,\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 arrival_airport_id\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY total_bookings \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 -- QUERY 5: Payment method success rate \cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5   \
    payment_method \cf2 \strokec6 AS\cf2 \strokec5  "Payment Method"\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Total Attempts"\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec6 CASE\cf2 \strokec5  \cf2 \strokec6 WHEN\cf2 \strokec5  payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec10 1\cf2 \strokec5  \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec10 0\cf2 \strokec5  \cf2 \strokec6 END\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Successful"\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec6 CASE\cf2 \strokec5  \cf2 \strokec6 WHEN\cf2 \strokec5  payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'NotConfirmed'\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec10 1\cf2 \strokec5  \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec10 0\cf2 \strokec5  \cf2 \strokec6 END\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Failed"\cf2 \strokec7 ,\cf2 \strokec5 \
    CONCAT\cf2 \strokec7 (\cf2 \strokec5 ROUND\cf2 \strokec7 (\cf2 \strokec5 SUM\cf2 \strokec7 (\cf2 \strokec6 CASE\cf2 \strokec5  \cf2 \strokec6 WHEN\cf2 \strokec5  payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec10 1\cf2 \strokec5  \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec10 0\cf2 \strokec5  \cf2 \strokec6 END\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec10 100.0\cf2 \strokec5  \cf2 \strokec8 /\cf2 \strokec5  COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 2\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec9 '%'\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Success Rate"\cf2 \strokec7 ,\cf2 \strokec5 \
    ROUND\cf2 \strokec7 (\cf2 \strokec5 AVG\cf2 \strokec7 (\cf2 \strokec5 amount\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 2\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Average Amount"\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec5 amount\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  "Total Amount Processed"\
\cf2 \strokec6 FROM\cf2 \strokec5  payments\
\cf2 \strokec6 GROUP\cf2 \strokec5  BY payment_method\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY "Success Rate" \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 -- QUERY 6:display the airlines names and codes in upper case and the total number of bookings every airline has , use COUNT() function and UPPER().\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  \
    UPPER\cf2 \strokec7 (\cf2 \strokec5 a\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  airline_names\cf2 \strokec7 ,\cf2 \strokec5 \
    a\cf2 \strokec7 .\cf2 \strokec5 airline_code\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_bookings\
\cf2 \strokec6 FROM\cf2 \strokec5  airlines a\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  flights f \cf2 \strokec6 ON\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_id \cf2 \strokec8 =\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 airline_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 flight_id \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 GROUP\cf2 \strokec5  BY a\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 ,\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_code\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY total_bookings \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --QUERY 7:Top 5 Bookings by Revenue\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 ,\cf2 \strokec5 \
    f\cf2 \strokec7 .\cf2 \strokec5 flight_number\cf2 \strokec7 ,\cf2 \strokec5 \
    a\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 ,\cf2 \strokec5 \
    CONCAT\cf2 \strokec7 (\cf2 \strokec5 dp\cf2 \strokec7 .\cf2 \strokec5 city\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 ' to '\cf2 \strokec7 ,\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 city\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Route\cf2 \strokec7 ,\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 total_price \cf2 \strokec6 AS\cf2 \strokec5  Booking_Revenue\
\cf2 \strokec6 FROM\cf2 \strokec5 \
    bookings b\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    flights f \cf2 \strokec6 ON\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 =\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 flight_id\
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    airlines a \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 airline_id \cf2 \strokec8 =\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_id\
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    airports dp \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 departure_airport_id \cf2 \strokec8 =\cf2 \strokec5  dp\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    airports arr \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 arrival_airport_id \cf2 \strokec8 =\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\cf2 \strokec6 ORDER\cf2 \strokec5  BY\
    Booking_Revenue \cf2 \strokec6 DESC\cf2 \strokec5 \
\cf2 \strokec6 LIMIT\cf2 \strokec5  \cf2 \strokec10 5\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
   \cf2 \strokec4 -- Query 8: Flight Routes Analysis (Domestic vs International)\cf2 \strokec5 \
\
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    dp\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec6 AS\cf2 \strokec5  Departure_Country\cf2 \strokec7 ,\cf2 \strokec5 \
    arr\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec6 AS\cf2 \strokec5  Arrival_Country\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec5 f\cf2 \strokec7 .\cf2 \strokec5 flight_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Total_Flights\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec6 DISTINCT\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 airline_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Distinct_Airlines\cf2 \strokec7 ,\cf2 \strokec5 \
    \cf2 \strokec6 CASE\cf2 \strokec5 \
        \cf2 \strokec6 WHEN\cf2 \strokec5  dp\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec8 =\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec9 'Domestic'\cf2 \strokec5 \
        \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec9 'International'\cf2 \strokec5 \
    \cf2 \strokec6 END\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Route_Type\
\cf2 \strokec6 FROM\cf2 \strokec5 \
    flights f\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    airports dp \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 departure_airport_id \cf2 \strokec8 =\cf2 \strokec5  dp\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    airports arr \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 arrival_airport_id \cf2 \strokec8 =\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 GROUP\cf2 \strokec5  BY\
    dp\cf2 \strokec7 .\cf2 \strokec5 country\cf2 \strokec7 ,\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 country\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY\
    Total_Flights \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
    \cf2 \strokec4 --Query 9: Payment Discount Calculation\cf2 \strokec5 \
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    payment_id\cf2 \strokec7 ,\cf2 \strokec5 \
    booking_id\cf2 \strokec7 ,\cf2 \strokec5 \
    amount \cf2 \strokec6 AS\cf2 \strokec5  Original_Amount\cf2 \strokec7 ,\cf2 \strokec5 \
    payment_method\cf2 \strokec7 ,\cf2 \strokec5 \
    ROUND\cf2 \strokec7 (\cf2 \strokec5 \
        \cf2 \strokec6 CASE\cf2 \strokec5 \
            \cf2 \strokec6 WHEN\cf2 \strokec5  payment_method \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'PAYPAL'\cf2 \strokec5  \cf2 \strokec8 OR\cf2 \strokec5  amount \cf2 \strokec8 >\cf2 \strokec5  \cf2 \strokec10 250.00\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  amount \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec10 0.05\cf2 \strokec5 \
            \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec10 0.00\cf2 \strokec5 \
        \cf2 \strokec6 END\cf2 \strokec7 ,\cf2 \strokec5 \
        \cf2 \strokec10 2\cf2 \strokec5 \
    \cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Discount_Applied\cf2 \strokec7 ,\cf2 \strokec5 \
    \cf2 \strokec7 (\cf2 \strokec5 amount \cf2 \strokec8 -\cf2 \strokec5  ROUND\cf2 \strokec7 (\cf2 \strokec5 \
        \cf2 \strokec6 CASE\cf2 \strokec5 \
            \cf2 \strokec6 WHEN\cf2 \strokec5  payment_method \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'PAYPAL'\cf2 \strokec5  \cf2 \strokec8 OR\cf2 \strokec5  amount \cf2 \strokec8 >\cf2 \strokec5  \cf2 \strokec10 250.00\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  amount \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec10 0.05\cf2 \strokec5 \
            \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec10 0.00\cf2 \strokec5 \
        \cf2 \strokec6 END\cf2 \strokec7 ,\cf2 \strokec5 \
        \cf2 \strokec10 2\cf2 \strokec5 \
    \cf2 \strokec7 ))\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Net_Revenue\
\cf2 \strokec6 FROM\cf2 \strokec5 \
    payments\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY\
    Discount_Applied \cf2 \strokec6 DESC\cf2 \strokec7 ,\cf2 \strokec5  payment_id\cf2 \strokec7 ;\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query 10: Passenger Meal Service Categorization\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  \cf2 \strokec6 DISTINCT\cf2 \strokec5  \cf2 \strokec6 ON\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec5 p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\cf2 \strokec7 )\cf2 \strokec5 \
    CONCAT\cf2 \strokec7 (\cf2 \strokec5 p\cf2 \strokec7 .\cf2 \strokec5 first_name\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec7 ,\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 last_name\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Full_Passenger_Name\cf2 \strokec7 ,\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 ,\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 ,\cf2 \strokec5 \
    \cf2 \strokec6 CASE\cf2 \strokec5 \
        \cf2 \strokec6 WHEN\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 total_price \cf2 \strokec8 >\cf2 \strokec5  \cf2 \strokec10 3000.00\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec9 'Premium Meal'\cf2 \strokec5 \
        \cf2 \strokec6 WHEN\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 total_price \cf2 \strokec8 >=\cf2 \strokec5  \cf2 \strokec10 1000.00\cf2 \strokec5  \cf2 \strokec8 AND\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 total_price \cf2 \strokec8 <=\cf2 \strokec5  \cf2 \strokec10 3000.00\cf2 \strokec5  \cf2 \strokec6 THEN\cf2 \strokec5  \cf2 \strokec9 'Standard Meal'\cf2 \strokec5 \
        \cf2 \strokec6 ELSE\cf2 \strokec5  \cf2 \strokec9 'Budget Meal'\cf2 \strokec5 \
    \cf2 \strokec6 END\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Meal_Service_Category\
\cf2 \strokec6 FROM\cf2 \strokec5 \
    passengers p\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5 \
    bookings b \cf2 \strokec6 ON\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 passenger_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 passenger_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 ORDER\cf2 \strokec5  BY\
    p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\cf2 \strokec7 ,\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 total_price \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query11:  Display the passenger full name, nationality, total confirmed spending, and rank passengers based on their total confirmed booking revenue. Show only the top 3 passengers\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WITH\cf2 \strokec5  passenger_revenue \cf2 \strokec6 AS\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec5 \
    \cf2 \strokec6 SELECT\cf2 \strokec5 \
        p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\cf2 \strokec7 ,\cf2 \strokec5 \
        p\cf2 \strokec7 .\cf2 \strokec5 first_name \cf2 \strokec8 ||\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec5  \cf2 \strokec8 ||\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 last_name \cf2 \strokec6 AS\cf2 \strokec5  full_name\cf2 \strokec7 ,\cf2 \strokec5 \
        p\cf2 \strokec7 .\cf2 \strokec5 nationality\cf2 \strokec7 ,\cf2 \strokec5 \
        SUM\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_spent\
    \cf2 \strokec6 FROM\cf2 \strokec5  passengers p\
    \cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 passenger_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 passenger_id\
    \cf2 \strokec6 WHERE\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
    \cf2 \strokec6 GROUP\cf2 \strokec5  BY p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec7 )\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    full_name\cf2 \strokec7 ,\cf2 \strokec5 \
    nationality\cf2 \strokec7 ,\cf2 \strokec5 \
    total_spent\cf2 \strokec7 ,\cf2 \strokec5 \
    RANK\cf2 \strokec7 ()\cf2 \strokec5  OVER \cf2 \strokec7 (\cf2 \strokec6 ORDER\cf2 \strokec5  BY total_spent \cf2 \strokec6 DESC\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  spending_rank\
\cf2 \strokec6 FROM\cf2 \strokec5  passenger_revenue\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY spending_rank\
\cf2 \strokec6 LIMIT\cf2 \strokec5  \cf2 \strokec10 3\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query12: Show each airline\'92s name, total available seats, total confirmed bookings, and seat utilization percentage. Only show airlines with utilization above 5%\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    a\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec5 f\cf2 \strokec7 .\cf2 \strokec5 available_seats\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_available_seats\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec6 DISTINCT\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  confirmed_bookings\cf2 \strokec7 ,\cf2 \strokec5 \
    ROUND\cf2 \strokec7 (\cf2 \strokec5 \
        COUNT\cf2 \strokec7 (\cf2 \strokec6 DISTINCT\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec10 100.0\cf2 \strokec5  \cf2 \strokec8 /\cf2 \strokec5  NULLIF\cf2 \strokec7 (\cf2 \strokec5 SUM\cf2 \strokec7 (\cf2 \strokec5 f\cf2 \strokec7 .\cf2 \strokec5 available_seats\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec10 0\cf2 \strokec7 ),\cf2 \strokec5 \
        \cf2 \strokec10 2\cf2 \strokec5 \
    \cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  utilization_percentage\
\cf2 \strokec6 FROM\cf2 \strokec5  airlines a\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  flights f \cf2 \strokec6 ON\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_id \cf2 \strokec8 =\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 airline_id\
\cf2 \strokec8 LEFT\cf2 \strokec5  \cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \
    \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 AND\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 GROUP\cf2 \strokec5  BY a\cf2 \strokec7 .\cf2 \strokec5 airline_name\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY utilization_percentage \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query13: Display flight number, airline name, total confirmed revenue per flight, and compare it to the global average confirmed flight revenue. Return only flights that exceed the average.\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    f\cf2 \strokec7 .\cf2 \strokec5 flight_number\cf2 \strokec7 ,\cf2 \strokec5 \
    a\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  flight_revenue\
\cf2 \strokec6 FROM\cf2 \strokec5  flights f\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  airlines a \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 airline_id \cf2 \strokec8 =\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 flight_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\cf2 \strokec6 GROUP\cf2 \strokec5  BY f\cf2 \strokec7 .\cf2 \strokec5 flight_id\cf2 \strokec7 ,\cf2 \strokec5  a\cf2 \strokec7 .\cf2 \strokec5 airline_name\
\cf2 \strokec6 HAVING\cf2 \strokec5  SUM\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec8 >\cf2 \strokec5 \
       \cf2 \strokec7 (\cf2 \strokec5 \
           \cf2 \strokec6 SELECT\cf2 \strokec5  AVG\cf2 \strokec7 (\cf2 \strokec5 flight_total\cf2 \strokec7 )\cf2 \strokec5 \
           \cf2 \strokec6 FROM\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec5 \
               \cf2 \strokec6 SELECT\cf2 \strokec5  SUM\cf2 \strokec7 (\cf2 \strokec5 b2\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  flight_total\
               \cf2 \strokec6 FROM\cf2 \strokec5  bookings b2\
               \cf2 \strokec6 WHERE\cf2 \strokec5  b2\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
               \cf2 \strokec6 GROUP\cf2 \strokec5  BY b2\cf2 \strokec7 .\cf2 \strokec5 flight_id\
           \cf2 \strokec7 )\cf2 \strokec5  sub\
       \cf2 \strokec7 )\cf2 \strokec5 \
\cf2 \strokec6 ORDER\cf2 \strokec5  BY flight_revenue \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query14: Display departure country, arrival country, total confirmed bookings, and total revenue between each country pair.\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    dep\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec6 AS\cf2 \strokec5  departure_country\cf2 \strokec7 ,\cf2 \strokec5 \
    arr\cf2 \strokec7 .\cf2 \strokec5 country \cf2 \strokec6 AS\cf2 \strokec5  arrival_country\cf2 \strokec7 ,\cf2 \strokec5 \
    COUNT\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 booking_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_confirmed_bookings\cf2 \strokec7 ,\cf2 \strokec5 \
    SUM\cf2 \strokec7 (\cf2 \strokec5 b\cf2 \strokec7 .\cf2 \strokec5 total_price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_revenue\
\cf2 \strokec6 FROM\cf2 \strokec5  flights f\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  airports dep \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 departure_airport_id \cf2 \strokec8 =\cf2 \strokec5  dep\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  airports arr \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 arrival_airport_id \cf2 \strokec8 =\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 airport_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  f\cf2 \strokec7 .\cf2 \strokec5 flight_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 flight_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\cf2 \strokec6 GROUP\cf2 \strokec5  BY dep\cf2 \strokec7 .\cf2 \strokec5 country\cf2 \strokec7 ,\cf2 \strokec5  arr\cf2 \strokec7 .\cf2 \strokec5 country\
\cf2 \strokec6 ORDER\cf2 \strokec5  BY total_revenue \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query 15: Create a unified financial report that combines confirmed booking revenue and confirmed payment revenue into a single result set.\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    \cf2 \strokec9 'Booking Revenue'\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Revenue_Source\cf2 \strokec7 ,\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 booking_id \cf2 \strokec6 AS\cf2 \strokec5  Reference_ID\cf2 \strokec7 ,\cf2 \strokec5 \
    p\cf2 \strokec7 .\cf2 \strokec5 first_name \cf2 \strokec8 ||\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec5  \cf2 \strokec8 ||\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 last_name \cf2 \strokec6 AS\cf2 \strokec5  Passenger_Name\cf2 \strokec7 ,\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 total_price \cf2 \strokec6 AS\cf2 \strokec5  Revenue_Amount\cf2 \strokec7 ,\cf2 \strokec5 \
    b\cf2 \strokec7 .\cf2 \strokec5 booking_date \cf2 \strokec6 AS\cf2 \strokec5  Revenue_Date\
\cf2 \strokec6 FROM\cf2 \strokec5  bookings b\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  passengers p \cf2 \strokec6 ON\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 passenger_id \cf2 \strokec8 =\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 UNION\cf2 \strokec5  \cf2 \strokec6 ALL\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5 \
    \cf2 \strokec9 'Payment Revenue'\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  Revenue_Source\cf2 \strokec7 ,\cf2 \strokec5 \
    pay\cf2 \strokec7 .\cf2 \strokec5 payment_id \cf2 \strokec6 AS\cf2 \strokec5  Reference_ID\cf2 \strokec7 ,\cf2 \strokec5 \
    p\cf2 \strokec7 .\cf2 \strokec5 first_name \cf2 \strokec8 ||\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec5  \cf2 \strokec8 ||\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 last_name \cf2 \strokec6 AS\cf2 \strokec5  Passenger_Name\cf2 \strokec7 ,\cf2 \strokec5 \
    pay\cf2 \strokec7 .\cf2 \strokec5 amount \cf2 \strokec6 AS\cf2 \strokec5  Revenue_Amount\cf2 \strokec7 ,\cf2 \strokec5 \
    pay\cf2 \strokec7 .\cf2 \strokec5 payment_date \cf2 \strokec6 AS\cf2 \strokec5  Revenue_Date\
\cf2 \strokec6 FROM\cf2 \strokec5  payments pay\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  pay\cf2 \strokec7 .\cf2 \strokec5 booking_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 booking_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  passengers p \cf2 \strokec6 ON\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 passenger_id \cf2 \strokec8 =\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  pay\cf2 \strokec7 .\cf2 \strokec5 payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\cf2 \strokec6 ORDER\cf2 \strokec5  BY Revenue_Amount \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query 16: \cf2 \strokec5 \
 \cf2 \strokec6 SELECT\cf2 \strokec5  airlines\cf2 \strokec7 .\cf2 \strokec5 airline_id\cf2 \strokec7 ,\cf2 \strokec5  airlines\cf2 \strokec7 .\cf2 \strokec5 airline_name\cf2 \strokec7 ,\cf2 \strokec5  AVG\cf2 \strokec7 (\cf2 \strokec5 flights\cf2 \strokec7 .\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  airline_avg\cf2 \strokec7 ,\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec7 (\cf2 \strokec6 SELECT\cf2 \strokec5  AVG\cf2 \strokec7 (\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 FROM\cf2 \strokec5  flights\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  global_avg\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 FROM\cf2 \strokec5  flights \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  airlines  \cf2 \strokec6 ON\cf2 \strokec5  flights\cf2 \strokec7 .\cf2 \strokec5 airline_id \cf2 \strokec8 =\cf2 \strokec5  airlines\cf2 \strokec7 .\cf2 \strokec5 airline_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 GROUP\cf2 \strokec5  BY airlines\cf2 \strokec7 .\cf2 \strokec5 airline_id\cf2 \strokec7 ,\cf2 \strokec5 airlines\cf2 \strokec7 .\cf2 \strokec5 airline_name\
\cf2 \strokec6 HAVING\cf2 \strokec5  AVG\cf2 \strokec7 (\cf2 \strokec5 flights\cf2 \strokec7 .\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec8 >\cf2 \strokec7 (\cf2 \strokec6 SELECT\cf2 \strokec5  AVG\cf2 \strokec7 (\cf2 \strokec5 price\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 FROM\cf2 \strokec5  flights\cf2 \strokec7 );\cf2 \strokec5 \
\
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query 17:display the nationality, the total number of passengers from that nationality and the total amount of completed payment revenue generated by each nationality. Use functions to sum only payments with a status of \'91confirmed\'92, group nationalities and alias payments revenue as 'total_revenue'\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 SELECT\cf2 \strokec5  nationality\cf2 \strokec7 ,\cf2 \strokec5  COUNT\cf2 \strokec7 (\cf2 \strokec6 DISTINCT\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 passenger_id\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_passengers\cf2 \strokec7 ,\cf2 \strokec5 \
SUM\cf2 \strokec7 (\cf2 \strokec5 pay\cf2 \strokec7 .\cf2 \strokec5 amount\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  total_revenue\
\cf2 \strokec6 FROM\cf2 \strokec5  passengers p \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 JOIN\cf2 \strokec5  bookings b \cf2 \strokec6 ON\cf2 \strokec5  p\cf2 \strokec7 .\cf2 \strokec5 passenger_id \cf2 \strokec8 =\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 passenger_id\
\cf2 \strokec8 JOIN\cf2 \strokec5  payments pay \cf2 \strokec6 ON\cf2 \strokec5  b\cf2 \strokec7 .\cf2 \strokec5 booking_id \cf2 \strokec8 =\cf2 \strokec5  pay\cf2 \strokec7 .\cf2 \strokec5 booking_id\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'confirmed'\cf2 \strokec5 \
\cf2 \strokec6 GROUP\cf2 \strokec5  BY nationality \
\cf2 \strokec6 ORDER\cf2 \strokec5  BY SUM\cf2 \strokec7 (\cf2 \strokec5 pay\cf2 \strokec7 .\cf2 \strokec5 amount\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 DESC\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query 18:Delete all payments that were not confirmed and change their bookings status to 'canceled'\cf2 \strokec5 \
BEGIN TRANSACTION\cf2 \strokec7 ;\cf2 \strokec5 \
DELETE \cf2 \strokec6 FROM\cf2 \strokec5  payments \cf2 \strokec6 WHERE\cf2 \strokec5  payment_status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'NotConfirmed'\cf2 \strokec7 ;\cf2 \strokec5 \
UPDATE bookings \
SET status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'Canceled'\cf2 \strokec5  \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec6 WHERE\cf2 \strokec5  booking_id \cf2 \strokec8 NOT\cf2 \strokec5  \cf2 \strokec8 IN\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec6 SELECT\cf2 \strokec5  booking_id \cf2 \strokec6 FROM\cf2 \strokec5  payments\cf2 \strokec7 );\cf2 \strokec5 \
\cf2 \strokec6 SELECT\cf2 \strokec5  \cf2 \strokec9 'Payments after cleanup:'\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  report\cf2 \strokec7 ;\cf2 \strokec5 \
\cf2 \strokec6 SELECT\cf2 \strokec5  \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec6 FROM\cf2 \strokec5  payments\cf2 \strokec7 ;\cf2 \strokec5 \
\cf2 \strokec6 SELECT\cf2 \strokec5  \cf2 \strokec9 'Bookings after update:'\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  report\cf2 \strokec7 ;\cf2 \strokec5   \
\cf2 \strokec6 SELECT\cf2 \strokec5  \cf2 \strokec8 *\cf2 \strokec5  \cf2 \strokec6 FROM\cf2 \strokec5  bookings \cf2 \strokec6 WHERE\cf2 \strokec5  status \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'Canceled'\cf2 \strokec7 ;\cf2 \strokec5 \
COMMIT\cf2 \strokec7 ;\cf2 \strokec5 \
\
\
\
\
\
\pard\pardeftab720\partightenfactor0
\cf2 \strokec4 --Query 19: Group passengers by nationality categories\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec7 (\cf2 \strokec5 \
    \cf2 \strokec6 SELECT\cf2 \strokec5  \
        \cf2 \strokec9 'Moroccan Passengers'\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  nationality_group\cf2 \strokec7 ,\cf2 \strokec5 \
        COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  passenger_count\cf2 \strokec7 ,\cf2 \strokec5 \
        STRING_AGG\cf2 \strokec7 (\cf2 \strokec5 CONCAT\cf2 \strokec7 (\cf2 \strokec5 first_name\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec7 ,\cf2 \strokec5  last_name\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec9 ', '\cf2 \strokec7 )\cf2 \strokec5  \cf2 \strokec6 AS\cf2 \strokec5  passenger_names\
    \cf2 \strokec6 FROM\cf2 \strokec5  passengers\
    \cf2 \strokec6 WHERE\cf2 \strokec5  nationality \cf2 \strokec8 =\cf2 \strokec5  \cf2 \strokec9 'Morocco'\cf2 \strokec5 \
\cf2 \strokec7 )\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 UNION\cf2 \strokec5  \cf2 \strokec6 ALL\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec7 (\cf2 \strokec5 \
    \cf2 \strokec6 SELECT\cf2 \strokec5  \
        \cf2 \strokec9 'European Passengers'\cf2 \strokec7 ,\cf2 \strokec5 \
        COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 ),\cf2 \strokec5 \
        STRING_AGG\cf2 \strokec7 (\cf2 \strokec5 CONCAT\cf2 \strokec7 (\cf2 \strokec5 first_name\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec7 ,\cf2 \strokec5  last_name\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec9 ', '\cf2 \strokec7 )\cf2 \strokec5 \
    \cf2 \strokec6 FROM\cf2 \strokec5  passengers\
    \cf2 \strokec6 WHERE\cf2 \strokec5  nationality \cf2 \strokec8 IN\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec9 'British'\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 'Germany'\cf2 \strokec7 )\cf2 \strokec5 \
\cf2 \strokec7 )\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec8 UNION\cf2 \strokec5  \cf2 \strokec6 ALL\cf2 \strokec5 \
\pard\pardeftab720\partightenfactor0
\cf2 \strokec7 (\cf2 \strokec5     \
    \cf2 \strokec6 SELECT\cf2 \strokec5  \
        \cf2 \strokec9 'Other Nationalities'\cf2 \strokec7 ,\cf2 \strokec5 \
        COUNT\cf2 \strokec7 (\cf2 \strokec8 *\cf2 \strokec7 ),\cf2 \strokec5 \
        STRING_AGG\cf2 \strokec7 (\cf2 \strokec5 CONCAT\cf2 \strokec7 (\cf2 \strokec5 first_name\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 ' '\cf2 \strokec7 ,\cf2 \strokec5  last_name\cf2 \strokec7 ),\cf2 \strokec5  \cf2 \strokec9 ', '\cf2 \strokec7 )\cf2 \strokec5 \
    \cf2 \strokec6 FROM\cf2 \strokec5  passengers\
    \cf2 \strokec6 WHERE\cf2 \strokec5  nationality \cf2 \strokec8 NOT\cf2 \strokec5  \cf2 \strokec8 IN\cf2 \strokec5  \cf2 \strokec7 (\cf2 \strokec9 'Morocco'\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 'British'\cf2 \strokec7 ,\cf2 \strokec5  \cf2 \strokec9 'Germany'\cf2 \strokec7 )\cf2 \strokec5 \
\cf2 \strokec7 );\cf2 \strokec5 \
}