--QUERY 1: Show revenue generated by each payment method for confirmed payments
SELECT 
    p.payment_method AS "Payment Method", 
    COUNT(*) AS "Number of Payments", 
    CONCAT('$', SUM(p.amount)) AS "Total Revenue", 
    CONCAT('$', ROUND(AVG(p.amount), 2)) AS "Average Payment",
    CONCAT(ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM payments WHERE payment_status = 'confirmed'), 2), '%') AS "Market Share"
FROM payments p
WHERE p.payment_status = 'confirmed' 
GROUP BY p.payment_method
ORDER BY SUM(p.amount) DESC;

-- QUERY 2: Passenger distribution by nationality 
SELECT 
    nationality AS "Nationality",
    COUNT(*) AS "Passenger Count",
    CONCAT(ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM passengers), 2), '%') AS "Percentage"
FROM passengers 
GROUP BY nationality 
ORDER BY COUNT(*) DESC;


-- QUERY 3: Flights with airline info 
SELECT 
    f.flight_number AS "Flight",
    a.airline_name AS "Airline",
    a.country AS "Airline Country",
    f.departure_time AS "Departure",
    f.arrival_time AS "Arrival",
    CONCAT('$', f.price) AS "Price",
    CASE 
        WHEN f.available_seats > 100 THEN 'High Availability'
        WHEN f.available_seats > 50 THEN 'Medium Availability'
        ELSE 'Low Availability'
    END AS "Seat Status"
FROM flights f
INNER JOIN airlines a ON f.airline_id = a.airline_id
WHERE a.country IN ('Turkey', 'Morocco', 'Germany')
ORDER BY f.price DESC, a.airline_name;





-- QUERY 4: Popular Routes Analysis )

SELECT 
    CONCAT(dep.city, ' → ', arr.city) AS route,
    COUNT(b.booking_id) AS total_bookings,
    SUM(b.total_price) AS total_revenue,
    MIN(f.price) AS cheapest_ticket,
    MAX(f.price) AS most_expensive_ticket,
    ROUND(AVG(f.price), 2) AS average_price
FROM flights f
JOIN airports dep ON f.departure_airport_id = dep.airport_id
JOIN airports arr ON f.arrival_airport_id = arr.airport_id
JOIN bookings b ON f.flight_id = b.flight_id
WHERE b.status = 'confirmed'
GROUP BY dep.city, arr.city, f.departure_airport_id, f.arrival_airport_id
ORDER BY total_bookings DESC;


-- QUERY 5: Payment method success rate 
SELECT  
    payment_method AS "Payment Method",
    COUNT(*) AS "Total Attempts",
    SUM(CASE WHEN payment_status = 'confirmed' THEN 1 ELSE 0 END) AS "Successful",
    SUM(CASE WHEN payment_status = 'NotConfirmed' THEN 1 ELSE 0 END) AS "Failed",
    CONCAT(ROUND(SUM(CASE WHEN payment_status = 'confirmed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2), '%') AS "Success Rate",
    ROUND(AVG(amount), 2) AS "Average Amount",
    SUM(amount) AS "Total Amount Processed"
FROM payments
GROUP BY payment_method
ORDER BY "Success Rate" DESC;


-- QUERY 6:display the airlines names and codes in upper case and the total number of bookings every airline has , use COUNT() function and UPPER().

SELECT 
    UPPER(a.airline_name) AS airline_names,
    a.airline_code,
    COUNT(b.booking_id) AS total_bookings
FROM airlines a
JOIN flights f ON a.airline_id = f.airline_id
JOIN bookings b ON f.flight_id = b.flight_id 
GROUP BY a.airline_name, a.airline_code
ORDER BY total_bookings DESC;

--QUERY 7:Top 5 Bookings by Revenue

SELECT
    b.booking_id,
    f.flight_number,
    a.airline_name,
    CONCAT(dp.city, ' to ', arr.city) AS Route,
    b.total_price AS Booking_Revenue
FROM
    bookings b
JOIN
    flights f ON b.flight_id = f.flight_id
JOIN
    airlines a ON f.airline_id = a.airline_id
JOIN
    airports dp ON f.departure_airport_id = dp.airport_id
JOIN
    airports arr ON f.arrival_airport_id = arr.airport_id
WHERE
    b.status = 'confirmed'
ORDER BY
    Booking_Revenue DESC
LIMIT 5;


   -- Query 8: Flight Routes Analysis (Domestic vs International)

SELECT
    dp.country AS Departure_Country,
    arr.country AS Arrival_Country,
    COUNT(f.flight_id) AS Total_Flights,
    COUNT(DISTINCT f.airline_id) AS Distinct_Airlines,
    CASE
        WHEN dp.country = arr.country THEN 'Domestic'
        ELSE 'International'
    END AS Route_Type
FROM
    flights f
JOIN
    airports dp ON f.departure_airport_id = dp.airport_id
JOIN
    airports arr ON f.arrival_airport_id = arr.airport_id
GROUP BY
    dp.country, arr.country
ORDER BY
    Total_Flights DESC;

    --Query 9: Payment Discount Calculation
SELECT
    payment_id,
    booking_id,
    amount AS Original_Amount,
    payment_method,
    ROUND(
        CASE
            WHEN payment_method = 'PAYPAL' OR amount > 250.00 THEN amount * 0.05
            ELSE 0.00
        END,
        2
    ) AS Discount_Applied,
    (amount - ROUND(
        CASE
            WHEN payment_method = 'PAYPAL' OR amount > 250.00 THEN amount * 0.05
            ELSE 0.00
        END,
        2
    )) AS Net_Revenue
FROM
    payments
ORDER BY
    Discount_Applied DESC, payment_id;

--Query 10: Passenger Meal Service Categorization

SELECT DISTINCT ON (p.passenger_id)
    CONCAT(p.first_name, ' ', p.last_name) AS Full_Passenger_Name,
    b.booking_id,
    b.total_price,
    CASE
        WHEN b.total_price > 3000.00 THEN 'Premium Meal'
        WHEN b.total_price >= 1000.00 AND b.total_price <= 3000.00 THEN 'Standard Meal'
        ELSE 'Budget Meal'
    END AS Meal_Service_Category
FROM
    passengers p
JOIN
    bookings b ON p.passenger_id = b.passenger_id
ORDER BY
    p.passenger_id, b.total_price DESC;


--Query11:  Display the passenger full name, nationality, total confirmed spending, and rank passengers based on their total confirmed booking revenue. Show only the top 3 passengers
WITH passenger_revenue AS (
    SELECT
        p.passenger_id,
        p.first_name || ' ' || p.last_name AS full_name,
        p.nationality,
        SUM(b.total_price) AS total_spent
    FROM passengers p
    JOIN bookings b ON p.passenger_id = b.passenger_id
    WHERE b.status = 'confirmed'
    GROUP BY p.passenger_id
)
SELECT
    full_name,
    nationality,
    total_spent,
    RANK() OVER (ORDER BY total_spent DESC) AS spending_rank
FROM passenger_revenue
ORDER BY spending_rank
LIMIT 3;



--Query12: Show each airline’s name, total available seats, total confirmed bookings, and seat utilization percentage. Only show airlines with utilization above 5%
SELECT
    a.airline_name,
    SUM(f.available_seats) AS total_available_seats,
    COUNT(DISTINCT b.booking_id) AS confirmed_bookings,
    ROUND(
        COUNT(DISTINCT b.booking_id) * 100.0 / NULLIF(SUM(f.available_seats), 0),
        2
    ) AS utilization_percentage
FROM airlines a
JOIN flights f ON a.airline_id = f.airline_id
LEFT JOIN bookings b 
    ON f.flight_id = b.flight_id AND b.status = 'confirmed'
GROUP BY a.airline_name
ORDER BY utilization_percentage DESC;

--Query13: Display flight number, airline name, total confirmed revenue per flight, and compare it to the global average confirmed flight revenue. Return only flights that exceed the average.
SELECT
    f.flight_number,
    a.airline_name,
    SUM(b.total_price) AS flight_revenue
FROM flights f
JOIN airlines a ON f.airline_id = a.airline_id
JOIN bookings b ON f.flight_id = b.flight_id
WHERE b.status = 'confirmed'
GROUP BY f.flight_id, a.airline_name
HAVING SUM(b.total_price) >
       (
           SELECT AVG(flight_total)
           FROM (
               SELECT SUM(b2.total_price) AS flight_total
               FROM bookings b2
               WHERE b2.status = 'confirmed'
               GROUP BY b2.flight_id
           ) sub
       )
ORDER BY flight_revenue DESC;



--Query14: Display departure country, arrival country, total confirmed bookings, and total revenue between each country pair.
SELECT
    dep.country AS departure_country,
    arr.country AS arrival_country,
    COUNT(b.booking_id) AS total_confirmed_bookings,
    SUM(b.total_price) AS total_revenue
FROM flights f
JOIN airports dep ON f.departure_airport_id = dep.airport_id
JOIN airports arr ON f.arrival_airport_id = arr.airport_id
JOIN bookings b ON f.flight_id = b.flight_id
WHERE b.status = 'confirmed'
GROUP BY dep.country, arr.country
ORDER BY total_revenue DESC;



--Query 15: Create a unified financial report that combines confirmed booking revenue and confirmed payment revenue into a single result set.
SELECT
    'Booking Revenue' AS Revenue_Source,
    b.booking_id AS Reference_ID,
    p.first_name || ' ' || p.last_name AS Passenger_Name,
    b.total_price AS Revenue_Amount,
    b.booking_date AS Revenue_Date
FROM bookings b
JOIN passengers p ON b.passenger_id = p.passenger_id
WHERE b.status = 'confirmed'
UNION ALL
SELECT
    'Payment Revenue' AS Revenue_Source,
    pay.payment_id AS Reference_ID,
    p.first_name || ' ' || p.last_name AS Passenger_Name,
    pay.amount AS Revenue_Amount,
    pay.payment_date AS Revenue_Date
FROM payments pay
JOIN bookings b ON pay.booking_id = b.booking_id
JOIN passengers p ON b.passenger_id = p.passenger_id
WHERE pay.payment_status = 'confirmed'
ORDER BY Revenue_Amount DESC;

--Query 16: 
 SELECT airlines.airline_id, airlines.airline_name, AVG(flights.price) AS airline_avg,
(SELECT AVG(price) FROM flights) AS global_avg
FROM flights 
JOIN airlines  ON flights.airline_id = airlines.airline_id
GROUP BY airlines.airline_id,airlines.airline_name
HAVING AVG(flights.price)>(SELECT AVG(price) FROM flights);



--Query 17:display the nationality, the total number of passengers from that nationality and the total amount of completed payment revenue generated by each nationality. Use functions to sum only payments with a status of ‘confirmed’, group nationalities and alias payments revenue as 'total_revenue'
SELECT nationality, COUNT(DISTINCT p.passenger_id) AS total_passengers,
SUM(pay.amount) AS total_revenue
FROM passengers p 
JOIN bookings b ON p.passenger_id = b.passenger_id
JOIN payments pay ON b.booking_id = pay.booking_id
WHERE payment_status = 'confirmed'
GROUP BY nationality 
ORDER BY SUM(pay.amount) DESC;


--Query 18:Delete all payments that were not confirmed and change their bookings status to 'canceled'
BEGIN TRANSACTION;
DELETE FROM payments WHERE payment_status = 'NotConfirmed';
UPDATE bookings 
SET status = 'Canceled' 
WHERE booking_id NOT IN (SELECT booking_id FROM payments);
SELECT 'Payments after cleanup:' AS report;
SELECT * FROM payments;
SELECT 'Bookings after update:' AS report;  
SELECT * FROM bookings WHERE status = 'Canceled';
COMMIT;





--Query 19: Group passengers by nationality categories
(
    SELECT 
        'Moroccan Passengers' AS nationality_group,
        COUNT(*) AS passenger_count,
        STRING_AGG(CONCAT(first_name, ' ', last_name), ', ') AS passenger_names
    FROM passengers
    WHERE nationality = 'Morocco'
)
UNION ALL
(
    SELECT 
        'European Passengers',
        COUNT(*),
        STRING_AGG(CONCAT(first_name, ' ', last_name), ', ')
    FROM passengers
    WHERE nationality IN ('British', 'Germany')
)
UNION ALL
(    
    SELECT 
        'Other Nationalities',
        COUNT(*),
        STRING_AGG(CONCAT(first_name, ' ', last_name), ', ')
    FROM passengers
    WHERE nationality NOT IN ('Morocco', 'British', 'Germany')
);
